theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - escondete-en-la-mano-del-senor.md
  - grande-eres-senor.md
  - incomparable.md
  - no-estoy-yo-aquí-que-soy-tu-madre.md
  - tu-senor.md
  
