theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - el-magnificant.md
  - escondete-en-la-mano-del-senor.md
  - grande-eres-senor.md
  - hasta-la-locura.md
  - incomparable.md
  - no-estoy-yo-aqui-que-soy-tu-madre.md
  - que-te-puedo-dars.md
  - quiero-alabarte-mas-y-mas-aun.md
  - tu-eres-nuestro-dios.md
  - tu-senor.md
  - tu-gran-amor.md
