theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Escóndete en la mano del señor.md
  - Grande eres Señor.md
  - Incomparable.md
  - Tu señor.md
  - ¿No estoy yo aquí que soy tu madre?.md
  
